services:
  api:
    build: .
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000" # Cổng cho API (Swagger UI)
      - "5678:5678" # Cổng "cửa hậu" cho VS Code Debugger
    volumes:
      - .:/app
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
